### PR TITLE
Allow text filenames, and run changesets serially.

### PR DESCRIPTION
**Pull request by mlohbihler**

### CODE REVIEW

**Review by rogierslag — APPROVED** [review]
Great!

I'll release this as a `2.0.0` release though since the database table needs to be updated as well

**Comment by mlohbihler** [comment]
Sounds good. Thanks Rogier. Note that i didn't increase the version that much because existing installations will still work the same way despite the changes.

**Comment by rogierslag** [comment]
Ive increased the version for release. The 2.0.0 version is available now on npm

**Comment by mlohbihler** [comment]
That's great. Thanks so much Rogier.

**Pull request merged**
